name: update book data conpass schedule # このワークフローの名前を記述（自由にきめてOK）
on:
  schedule:
    - cron: "0 15 * * *" # 午前0時に実行(UTC基準なので9時間引く)
  workflow_dispatch:
jobs:
  bookDataUpdate:
    permissions:
      actions: write
      checks: write
      contents: write
    runs-on: ubuntu-latest # 最新のubuntu環境で下記のジョブを実行
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2 # pythonをセットアップ
        with:
          python-version: "3.9" # pythonのバージョンを指定
          architecture: "x64" # アーキテクチャを指定
      - name: pip setting
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install bs4
      - name: run python
        working-directory: src/python # scriptsのファイルを指定
        run: |
          python scraping.py
      - name: Set up Git
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Check for changes
        id: check_changes
        run: |
          changes=$(git diff --name-only)
          if [ -z "$changes" ]; then
            echo "No changes detected. Exiting..."
          else
            echo "Changes detected: $changes"
            git config --global user.name "${{ github.actor }}"
            git config --global user.email "${{ github.actor }}@users.noreply.github.com"
            git add src/python/book_data.json
            git commit -m 'update book-data.json'
            git push origin main
          fi
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '10'
      - name: Install dependencies
        run: npm install
      - name: deploy
        run: |
          npm run deploy
